### ISSUE TITLE
Feature Request: Sentence spaced ngrams file

### ISSUE THREAD

**Issue by brubsby** [doranchak/azdecrypt#3]
A cipher I want to solve seems to use spaces at the end of each sentence but not between words. I know the trick about removing spaces with `Substitution + units`, but as I need to also do transposition and/or crib grid at the same time, it doesn't seem like a feasible option. I'd create my own ngrams file with this criteria met, but I'm uncertain the exact format used, and what tools have been used to assist in the creation of a file (rewriting my own seems a bit daunting)

**Comment by doranchak** [comment]
Jarl believes that such a cipher scheme wouldn't complicate things very much as the standard n-grams would still solve it easily.  But if you wish to create your own ngrams file, there is a readme file with details of the format here:  https://github.com/doranchak/azdecrypt/tree/main/AZdecrypt/N-grams

**Comment by brubsby** [comment]
Jarl's belief in the standard n-grams' ability to solve such a cipher scheme is sufficient to convince me that my effort is better spent investigating other avenues for the time being! I appreciate the response and I'll keep the link handy for future reference though.
